### ISSUE TITLE
Unprotected previously protected sheets

### ISSUE THREAD

**Issue by bzorn** [plasma-umass/ExceLint-addin#13]
If a sheet is protected, and you run ExceLint, that sheet will no longer be protected after you "Restore".

**To Reproduce**
1. Enter a value in a cell
2. Protect the sheet
3. ExceLint "Reveal" then "Restore"
4. Sheet is no longer protected

Needs to remember the previous protected state when Restoring.

**Comment by emeryberger** [comment]
Fixed with https://github.com/plasma-umass/ExceLint-addin/commit/41b5b4b21c1a9fa5a2df1134f11d6913001f6ba3.

**Comment by emeryberger** [comment]
I now encode the protected status of the original worksheet in the backup sheet (which holds the original formats and values). If no such sheet exists, that means that there's nothing to restore, so now that is a NOP. If a sheet does exist, ExceLint restores it, and then uses the backup sheet's protection status to decide whether to protect the original sheet or not (that is, restoring its protection status as well).
