### ISSUE TITLE
Question about installation

### ISSUE THREAD

**Issue by fthompso** [plasma-umass/ExceLint-addin#14]
Hi. This is a fantastic tool, thank you for developing it. Is there a way to install the tool _without_ side-loading the add-in for testing? I would like to use it, but cannot share information from the sheets I'm working on.

Thanks,
Fraser

**Comment by emeryberger** [comment]
Hi - no information is shared with any server. *All* processing is done locally; the server just hosts the code and performs hot updates.

**Comment by emeryberger** [comment]
If you felt comfortable doing so, you could also run the server yourself client-side.
